package org.maracas.delta.internal;

import org.eclipse.jdt.core.ITypeParameter;

import io.usethesource.vallang.IBool;
import io.usethesource.vallang.IConstructor;
import io.usethesource.vallang.IInteger;
import io.usethesource.vallang.IList;
import io.usethesource.vallang.IString;

public interface JApiCmpBuilder {

	IConstructor getApiEntityClassCons(IString fullyQualifiedName, IConstructor classType, IList entities, IList compatibilityChanges, IConstructor apiChange);
	IConstructor getApiEntityInterfaceCons(IString fullyQualifiedName, IConstructor apiChange);
	IConstructor getApiEntityFieldCons(IInteger name, IString cachedName, IList entities, IList compatibilityChanges, IConstructor apiChange);
	IConstructor getApiEntityMethodCons(IString name, IConstructor returnType, IList entities, IList compatibilityChanges, IConstructor apiChange);
	IConstructor getApiEntityConstructorCons(IString name, IList entities, IList compatibilityChanges, IConstructor apiChange);
	IConstructor getApiEntityAnnotationCons(IString fullyQualifiedName, IList entities, IConstructor apiChange);
	IConstructor getApiEntityAnnotationElementCons(IString name, IConstructor apiChange);
	IConstructor getApiEntityExceptionCons(IString name, IBool checkedException, IConstructor apiChange);
	IConstructor getApiEntityParameterCons(IString type);
	IConstructor getApiEntityModifierCons(IConstructor apiChange);
	IConstructor getApiEntitySuperclassCons(IConstructor apiChange);
	IConstructor getApiChangeNewCons(ITypeParameter elem);
	IConstructor getApiChangeRemovedCons(ITypeParameter elem);
	IConstructor getApiChangeUnchangedCons();
	IConstructor getApiChangeModifiedCons(ITypeParameter oldElem, ITypeParameter newElem);
	IConstructor getApiChangeStatusNewCons();
	IConstructor getApiChangeStatusRemovedCons();
	IConstructor getApiChangeStatusUnchangedCons();
	IConstructor getApiChangeStatusModifiedCons();
	IConstructor getApiEntityClassTypeCons(IConstructor apiChange);
	IConstructor getApiEntityReturnTypeCons(IConstructor apiChange);
	IConstructor getMethodInfoCons(IInteger name, IString cachedName);
	IConstructor getCompatibilityChangeCons(IConstructor compatibilityChange, IBool binaryCompatible, IBool sourceCompatible);
	IConstructor getCCTAnnotationDeprecatedAdded();
	IConstructor getCCTClassRemoved();
	IConstructor getCCTClassNowAbstract();
	IConstructor getCCTClassNowFinal();
	IConstructor getCCTClassNoLongerPublic();
	IConstructor getCCTClassTypeChanged();
	IConstructor getCCTClassNowCheckedException();
	IConstructor getCCTClassLessAccessible();
	IConstructor getCCTSuperclassRemoved();
	IConstructor getCCTSuperclassAdded();
	IConstructor getCCTSuperclassModifiedIncompatible();
	IConstructor getCCTInterfaceAdded();
	IConstructor getCCTInterfaceRemoved();
	IConstructor getCCTMethodRemoved();
	IConstructor getCCTMethodRemovedInSuperclass();
	IConstructor getCCTMethodLessAccessible();
	IConstructor getCCTMethodLessAccessibleThanInSuperclass();
	IConstructor getCCTMethodIsStaticAndOverridesNotStatic();
	IConstructor getCCTMethodReturnTypeChanged();
	IConstructor getCCTMethodNowAbstract();
	IConstructor getCCTMethodNowFinal();
	IConstructor getCCTMethodNowStatic();
	IConstructor getCCTMethodNoLongerStatic();
	IConstructor getCCTMethodAddedToInterface();
	IConstructor getCCTMethodNowThrowsCheckedException();
	IConstructor getCCTMethodAbstractAddedToClass();
	IConstructor getCCTMethodAbstractAddedInSuperclass();
	IConstructor getCCTMethodAbstractAddedInImplementedInterface();
	IConstructor getCCTMethodNewDefault();
	IConstructor getCCTMethodAbstractNowDefault();
	IConstructor getCCTFieldStaticAndOverridesStatic();
	IConstructor getCCTFieldLessAccessibleThanInSuperclass();
	IConstructor getCCTFieldNowFinal();
	IConstructor getCCTFieldNowStatic();
	IConstructor getCCTFieldNoLongerStatic();
	IConstructor getCCTFieldTypeChanged();
	IConstructor getCCTFieldRemoved();
	IConstructor getCCTFieldRemovedInSuperclass();
	IConstructor getCCTFieldLessAccessible();
	IConstructor getCCTConstructorRemoved();
	IConstructor getCCTConstructorLessAccessible();
	IConstructor getClassTypeAnnotationCons();
	IConstructor getClassTypeInterfaceCons();
	IConstructor getClassTypeClassCons();
	IConstructor getClassTypeEnumCons();
	IConstructor getModifierPublicCons();
	IConstructor getModifierPrivateCons();
	IConstructor getModifierProtectedCons();
	IConstructor getModifierPackageProtectedCons();
	IConstructor getModifierFinalCons();
	IConstructor getModifierNonFinalCons();
	IConstructor getModifierStaticCons();
	IConstructor getModifierNonStaticCons();
	IConstructor getModifierAbstractCons();
	IConstructor getModifierNonAbstractCons();
	IConstructor getModifierSyntheticCons();
	IConstructor getModifierNonSyntheticCons();
	IConstructor getModifierBridgeCons();
	IConstructor getModifierNonBridgeCons();
}
