// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent/spanAgent.proto

package com.expedia.open.tracing.agent.api;

public final class SpanAgentOuterClass {
  private SpanAgentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DispatchResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DispatchResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025agent/spanAgent.proto\032\nspan.proto\"\225\001\n\016" +
      "DispatchResult\022(\n\004code\030\001 \001(\0162\032.DispatchR" +
      "esult.ResultCode\022\025\n\rerror_message\030\002 \001(\t\"" +
      "B\n\nResultCode\022\013\n\007SUCCESS\020\000\022\021\n\rUNKNOWN_ER" +
      "ROR\020\001\022\024\n\020RATE_LIMIT_ERROR\020\0022/\n\tSpanAgent" +
      "\022\"\n\010dispatch\022\005.Span\032\017.DispatchResultB&\n\"" +
      "com.expedia.open.tracing.agent.apiP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.expedia.open.tracing.SpanOuterClass.getDescriptor(),
        }, assigner);
    internal_static_DispatchResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DispatchResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DispatchResult_descriptor,
        new java.lang.String[] { "Code", "ErrorMessage", });
    com.expedia.open.tracing.SpanOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
