// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

public interface CallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Call)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * service node from which call was started
   * </pre>
   *
   * <code>optional .CallNode from = 1;</code>
   */
  boolean hasFrom();
  /**
   * <pre>
   * service node from which call was started
   * </pre>
   *
   * <code>optional .CallNode from = 1;</code>
   */
  com.expedia.open.tracing.api.CallNode getFrom();
  /**
   * <pre>
   * service node from which call was started
   * </pre>
   *
   * <code>optional .CallNode from = 1;</code>
   */
  com.expedia.open.tracing.api.CallNodeOrBuilder getFromOrBuilder();

  /**
   * <pre>
   * service node to which call was terminated
   * </pre>
   *
   * <code>optional .CallNode to = 2;</code>
   */
  boolean hasTo();
  /**
   * <pre>
   * service node to which call was terminated
   * </pre>
   *
   * <code>optional .CallNode to = 2;</code>
   */
  com.expedia.open.tracing.api.CallNode getTo();
  /**
   * <pre>
   * service node to which call was terminated
   * </pre>
   *
   * <code>optional .CallNode to = 2;</code>
   */
  com.expedia.open.tracing.api.CallNodeOrBuilder getToOrBuilder();

  /**
   * <pre>
   * time delta in transit
   * </pre>
   *
   * <code>optional int64 networkDelta = 3;</code>
   */
  long getNetworkDelta();
}
