// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
