// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

public interface FieldNamesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FieldNames)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string names = 1;</code>
   */
  java.util.List<java.lang.String>
      getNamesList();
  /**
   * <code>repeated string names = 1;</code>
   */
  int getNamesCount();
  /**
   * <code>repeated string names = 1;</code>
   */
  java.lang.String getNames(int index);
  /**
   * <code>repeated string names = 1;</code>
   */
  com.google.protobuf.ByteString
      getNamesBytes(int index);
}
