// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

public interface FieldValuesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FieldValuesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name of field to query for
   * </pre>
   *
   * <code>optional string fieldName = 1;</code>
   */
  java.lang.String getFieldName();
  /**
   * <pre>
   * name of field to query for
   * </pre>
   *
   * <code>optional string fieldName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFieldNameBytes();

  /**
   * <pre>
   * provided fields to be used for filtering
   * </pre>
   *
   * <code>repeated .Field filters = 2;</code>
   */
  java.util.List<com.expedia.open.tracing.api.Field> 
      getFiltersList();
  /**
   * <pre>
   * provided fields to be used for filtering
   * </pre>
   *
   * <code>repeated .Field filters = 2;</code>
   */
  com.expedia.open.tracing.api.Field getFilters(int index);
  /**
   * <pre>
   * provided fields to be used for filtering
   * </pre>
   *
   * <code>repeated .Field filters = 2;</code>
   */
  int getFiltersCount();
  /**
   * <pre>
   * provided fields to be used for filtering
   * </pre>
   *
   * <code>repeated .Field filters = 2;</code>
   */
  java.util.List<? extends com.expedia.open.tracing.api.FieldOrBuilder> 
      getFiltersOrBuilderList();
  /**
   * <pre>
   * provided fields to be used for filtering
   * </pre>
   *
   * <code>repeated .Field filters = 2;</code>
   */
  com.expedia.open.tracing.api.FieldOrBuilder getFiltersOrBuilder(
      int index);
}
