// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

public interface TraceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TraceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string traceId = 1;</code>
   */
  java.lang.String getTraceId();
  /**
   * <code>optional string traceId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();
}
