// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

/**
 * Protobuf type {@code TraceCallGraph}
 */
public  final class TraceCallGraph extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TraceCallGraph)
    TraceCallGraphOrBuilder {
  // Use TraceCallGraph.newBuilder() to construct.
  private TraceCallGraph(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TraceCallGraph() {
    calls_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TraceCallGraph(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              calls_ = new java.util.ArrayList<com.expedia.open.tracing.api.Call>();
              mutable_bitField0_ |= 0x00000001;
            }
            calls_.add(
                input.readMessage(com.expedia.open.tracing.api.Call.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        calls_ = java.util.Collections.unmodifiableList(calls_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TraceCallGraph_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TraceCallGraph_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.expedia.open.tracing.api.TraceCallGraph.class, com.expedia.open.tracing.api.TraceCallGraph.Builder.class);
  }

  public static final int CALLS_FIELD_NUMBER = 1;
  private java.util.List<com.expedia.open.tracing.api.Call> calls_;
  /**
   * <pre>
   * list of service calls
   * </pre>
   *
   * <code>repeated .Call calls = 1;</code>
   */
  public java.util.List<com.expedia.open.tracing.api.Call> getCallsList() {
    return calls_;
  }
  /**
   * <pre>
   * list of service calls
   * </pre>
   *
   * <code>repeated .Call calls = 1;</code>
   */
  public java.util.List<? extends com.expedia.open.tracing.api.CallOrBuilder> 
      getCallsOrBuilderList() {
    return calls_;
  }
  /**
   * <pre>
   * list of service calls
   * </pre>
   *
   * <code>repeated .Call calls = 1;</code>
   */
  public int getCallsCount() {
    return calls_.size();
  }
  /**
   * <pre>
   * list of service calls
   * </pre>
   *
   * <code>repeated .Call calls = 1;</code>
   */
  public com.expedia.open.tracing.api.Call getCalls(int index) {
    return calls_.get(index);
  }
  /**
   * <pre>
   * list of service calls
   * </pre>
   *
   * <code>repeated .Call calls = 1;</code>
   */
  public com.expedia.open.tracing.api.CallOrBuilder getCallsOrBuilder(
      int index) {
    return calls_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < calls_.size(); i++) {
      output.writeMessage(1, calls_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < calls_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, calls_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.expedia.open.tracing.api.TraceCallGraph)) {
      return super.equals(obj);
    }
    com.expedia.open.tracing.api.TraceCallGraph other = (com.expedia.open.tracing.api.TraceCallGraph) obj;

    boolean result = true;
    result = result && getCallsList()
        .equals(other.getCallsList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getCallsCount() > 0) {
      hash = (37 * hash) + CALLS_FIELD_NUMBER;
      hash = (53 * hash) + getCallsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.expedia.open.tracing.api.TraceCallGraph parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.expedia.open.tracing.api.TraceCallGraph parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TraceCallGraph parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.expedia.open.tracing.api.TraceCallGraph parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TraceCallGraph parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.expedia.open.tracing.api.TraceCallGraph parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TraceCallGraph parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.expedia.open.tracing.api.TraceCallGraph parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TraceCallGraph parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.expedia.open.tracing.api.TraceCallGraph parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.expedia.open.tracing.api.TraceCallGraph prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TraceCallGraph}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TraceCallGraph)
      com.expedia.open.tracing.api.TraceCallGraphOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TraceCallGraph_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TraceCallGraph_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.expedia.open.tracing.api.TraceCallGraph.class, com.expedia.open.tracing.api.TraceCallGraph.Builder.class);
    }

    // Construct using com.expedia.open.tracing.api.TraceCallGraph.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCallsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (callsBuilder_ == null) {
        calls_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        callsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TraceCallGraph_descriptor;
    }

    public com.expedia.open.tracing.api.TraceCallGraph getDefaultInstanceForType() {
      return com.expedia.open.tracing.api.TraceCallGraph.getDefaultInstance();
    }

    public com.expedia.open.tracing.api.TraceCallGraph build() {
      com.expedia.open.tracing.api.TraceCallGraph result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.expedia.open.tracing.api.TraceCallGraph buildPartial() {
      com.expedia.open.tracing.api.TraceCallGraph result = new com.expedia.open.tracing.api.TraceCallGraph(this);
      int from_bitField0_ = bitField0_;
      if (callsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          calls_ = java.util.Collections.unmodifiableList(calls_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.calls_ = calls_;
      } else {
        result.calls_ = callsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.expedia.open.tracing.api.TraceCallGraph) {
        return mergeFrom((com.expedia.open.tracing.api.TraceCallGraph)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.expedia.open.tracing.api.TraceCallGraph other) {
      if (other == com.expedia.open.tracing.api.TraceCallGraph.getDefaultInstance()) return this;
      if (callsBuilder_ == null) {
        if (!other.calls_.isEmpty()) {
          if (calls_.isEmpty()) {
            calls_ = other.calls_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCallsIsMutable();
            calls_.addAll(other.calls_);
          }
          onChanged();
        }
      } else {
        if (!other.calls_.isEmpty()) {
          if (callsBuilder_.isEmpty()) {
            callsBuilder_.dispose();
            callsBuilder_ = null;
            calls_ = other.calls_;
            bitField0_ = (bitField0_ & ~0x00000001);
            callsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCallsFieldBuilder() : null;
          } else {
            callsBuilder_.addAllMessages(other.calls_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.expedia.open.tracing.api.TraceCallGraph parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.expedia.open.tracing.api.TraceCallGraph) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.expedia.open.tracing.api.Call> calls_ =
      java.util.Collections.emptyList();
    private void ensureCallsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        calls_ = new java.util.ArrayList<com.expedia.open.tracing.api.Call>(calls_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.expedia.open.tracing.api.Call, com.expedia.open.tracing.api.Call.Builder, com.expedia.open.tracing.api.CallOrBuilder> callsBuilder_;

    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public java.util.List<com.expedia.open.tracing.api.Call> getCallsList() {
      if (callsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(calls_);
      } else {
        return callsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public int getCallsCount() {
      if (callsBuilder_ == null) {
        return calls_.size();
      } else {
        return callsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public com.expedia.open.tracing.api.Call getCalls(int index) {
      if (callsBuilder_ == null) {
        return calls_.get(index);
      } else {
        return callsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public Builder setCalls(
        int index, com.expedia.open.tracing.api.Call value) {
      if (callsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCallsIsMutable();
        calls_.set(index, value);
        onChanged();
      } else {
        callsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public Builder setCalls(
        int index, com.expedia.open.tracing.api.Call.Builder builderForValue) {
      if (callsBuilder_ == null) {
        ensureCallsIsMutable();
        calls_.set(index, builderForValue.build());
        onChanged();
      } else {
        callsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public Builder addCalls(com.expedia.open.tracing.api.Call value) {
      if (callsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCallsIsMutable();
        calls_.add(value);
        onChanged();
      } else {
        callsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public Builder addCalls(
        int index, com.expedia.open.tracing.api.Call value) {
      if (callsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCallsIsMutable();
        calls_.add(index, value);
        onChanged();
      } else {
        callsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public Builder addCalls(
        com.expedia.open.tracing.api.Call.Builder builderForValue) {
      if (callsBuilder_ == null) {
        ensureCallsIsMutable();
        calls_.add(builderForValue.build());
        onChanged();
      } else {
        callsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public Builder addCalls(
        int index, com.expedia.open.tracing.api.Call.Builder builderForValue) {
      if (callsBuilder_ == null) {
        ensureCallsIsMutable();
        calls_.add(index, builderForValue.build());
        onChanged();
      } else {
        callsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public Builder addAllCalls(
        java.lang.Iterable<? extends com.expedia.open.tracing.api.Call> values) {
      if (callsBuilder_ == null) {
        ensureCallsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, calls_);
        onChanged();
      } else {
        callsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public Builder clearCalls() {
      if (callsBuilder_ == null) {
        calls_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        callsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public Builder removeCalls(int index) {
      if (callsBuilder_ == null) {
        ensureCallsIsMutable();
        calls_.remove(index);
        onChanged();
      } else {
        callsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public com.expedia.open.tracing.api.Call.Builder getCallsBuilder(
        int index) {
      return getCallsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public com.expedia.open.tracing.api.CallOrBuilder getCallsOrBuilder(
        int index) {
      if (callsBuilder_ == null) {
        return calls_.get(index);  } else {
        return callsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public java.util.List<? extends com.expedia.open.tracing.api.CallOrBuilder> 
         getCallsOrBuilderList() {
      if (callsBuilder_ != null) {
        return callsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(calls_);
      }
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public com.expedia.open.tracing.api.Call.Builder addCallsBuilder() {
      return getCallsFieldBuilder().addBuilder(
          com.expedia.open.tracing.api.Call.getDefaultInstance());
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public com.expedia.open.tracing.api.Call.Builder addCallsBuilder(
        int index) {
      return getCallsFieldBuilder().addBuilder(
          index, com.expedia.open.tracing.api.Call.getDefaultInstance());
    }
    /**
     * <pre>
     * list of service calls
     * </pre>
     *
     * <code>repeated .Call calls = 1;</code>
     */
    public java.util.List<com.expedia.open.tracing.api.Call.Builder> 
         getCallsBuilderList() {
      return getCallsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.expedia.open.tracing.api.Call, com.expedia.open.tracing.api.Call.Builder, com.expedia.open.tracing.api.CallOrBuilder> 
        getCallsFieldBuilder() {
      if (callsBuilder_ == null) {
        callsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.expedia.open.tracing.api.Call, com.expedia.open.tracing.api.Call.Builder, com.expedia.open.tracing.api.CallOrBuilder>(
                calls_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        calls_ = null;
      }
      return callsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:TraceCallGraph)
  }

  // @@protoc_insertion_point(class_scope:TraceCallGraph)
  private static final com.expedia.open.tracing.api.TraceCallGraph DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.expedia.open.tracing.api.TraceCallGraph();
  }

  public static com.expedia.open.tracing.api.TraceCallGraph getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TraceCallGraph>
      PARSER = new com.google.protobuf.AbstractParser<TraceCallGraph>() {
    public TraceCallGraph parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TraceCallGraph(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TraceCallGraph> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TraceCallGraph> getParserForType() {
    return PARSER;
  }

  public com.expedia.open.tracing.api.TraceCallGraph getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

