// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

public interface TraceCallGraphOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TraceCallGraph)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * list of service calls
   * </pre>
   *
   * <code>repeated .Call calls = 1;</code>
   */
  java.util.List<com.expedia.open.tracing.api.Call> 
      getCallsList();
  /**
   * <pre>
   * list of service calls
   * </pre>
   *
   * <code>repeated .Call calls = 1;</code>
   */
  com.expedia.open.tracing.api.Call getCalls(int index);
  /**
   * <pre>
   * list of service calls
   * </pre>
   *
   * <code>repeated .Call calls = 1;</code>
   */
  int getCallsCount();
  /**
   * <pre>
   * list of service calls
   * </pre>
   *
   * <code>repeated .Call calls = 1;</code>
   */
  java.util.List<? extends com.expedia.open.tracing.api.CallOrBuilder> 
      getCallsOrBuilderList();
  /**
   * <pre>
   * list of service calls
   * </pre>
   *
   * <code>repeated .Call calls = 1;</code>
   */
  com.expedia.open.tracing.api.CallOrBuilder getCallsOrBuilder(
      int index);
}
