// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

/**
 * <pre>
 * criteria for searching traces
 * </pre>
 *
 * Protobuf type {@code TracesSearchRequest}
 */
public  final class TracesSearchRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TracesSearchRequest)
    TracesSearchRequestOrBuilder {
  // Use TracesSearchRequest.newBuilder() to construct.
  private TracesSearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TracesSearchRequest() {
    fields_ = java.util.Collections.emptyList();
    startTime_ = 0L;
    endTime_ = 0L;
    limit_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TracesSearchRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              fields_ = new java.util.ArrayList<com.expedia.open.tracing.api.Field>();
              mutable_bitField0_ |= 0x00000001;
            }
            fields_.add(
                input.readMessage(com.expedia.open.tracing.api.Field.parser(), extensionRegistry));
            break;
          }
          case 16: {

            startTime_ = input.readInt64();
            break;
          }
          case 24: {

            endTime_ = input.readInt64();
            break;
          }
          case 32: {

            limit_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        fields_ = java.util.Collections.unmodifiableList(fields_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TracesSearchRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TracesSearchRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.expedia.open.tracing.api.TracesSearchRequest.class, com.expedia.open.tracing.api.TracesSearchRequest.Builder.class);
  }

  private int bitField0_;
  public static final int FIELDS_FIELD_NUMBER = 1;
  private java.util.List<com.expedia.open.tracing.api.Field> fields_;
  /**
   * <pre>
   * fields to filter traces
   * </pre>
   *
   * <code>repeated .Field fields = 1;</code>
   */
  public java.util.List<com.expedia.open.tracing.api.Field> getFieldsList() {
    return fields_;
  }
  /**
   * <pre>
   * fields to filter traces
   * </pre>
   *
   * <code>repeated .Field fields = 1;</code>
   */
  public java.util.List<? extends com.expedia.open.tracing.api.FieldOrBuilder> 
      getFieldsOrBuilderList() {
    return fields_;
  }
  /**
   * <pre>
   * fields to filter traces
   * </pre>
   *
   * <code>repeated .Field fields = 1;</code>
   */
  public int getFieldsCount() {
    return fields_.size();
  }
  /**
   * <pre>
   * fields to filter traces
   * </pre>
   *
   * <code>repeated .Field fields = 1;</code>
   */
  public com.expedia.open.tracing.api.Field getFields(int index) {
    return fields_.get(index);
  }
  /**
   * <pre>
   * fields to filter traces
   * </pre>
   *
   * <code>repeated .Field fields = 1;</code>
   */
  public com.expedia.open.tracing.api.FieldOrBuilder getFieldsOrBuilder(
      int index) {
    return fields_.get(index);
  }

  public static final int STARTTIME_FIELD_NUMBER = 2;
  private long startTime_;
  /**
   * <pre>
   * search window start time in microseconds time from epoch
   * </pre>
   *
   * <code>optional int64 startTime = 2;</code>
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 3;
  private long endTime_;
  /**
   * <pre>
   * search window end time in microseconds time from epoch
   * </pre>
   *
   * <code>optional int64 endTime = 3;</code>
   */
  public long getEndTime() {
    return endTime_;
  }

  public static final int LIMIT_FIELD_NUMBER = 4;
  private int limit_;
  /**
   * <pre>
   * limit on number of results to return
   * </pre>
   *
   * <code>optional int32 limit = 4;</code>
   */
  public int getLimit() {
    return limit_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < fields_.size(); i++) {
      output.writeMessage(1, fields_.get(i));
    }
    if (startTime_ != 0L) {
      output.writeInt64(2, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(3, endTime_);
    }
    if (limit_ != 0) {
      output.writeInt32(4, limit_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < fields_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, fields_.get(i));
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, endTime_);
    }
    if (limit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, limit_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.expedia.open.tracing.api.TracesSearchRequest)) {
      return super.equals(obj);
    }
    com.expedia.open.tracing.api.TracesSearchRequest other = (com.expedia.open.tracing.api.TracesSearchRequest) obj;

    boolean result = true;
    result = result && getFieldsList()
        .equals(other.getFieldsList());
    result = result && (getStartTime()
        == other.getStartTime());
    result = result && (getEndTime()
        == other.getEndTime());
    result = result && (getLimit()
        == other.getLimit());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getFieldsCount() > 0) {
      hash = (37 * hash) + FIELDS_FIELD_NUMBER;
      hash = (53 * hash) + getFieldsList().hashCode();
    }
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLimit();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.expedia.open.tracing.api.TracesSearchRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.expedia.open.tracing.api.TracesSearchRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TracesSearchRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.expedia.open.tracing.api.TracesSearchRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TracesSearchRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.expedia.open.tracing.api.TracesSearchRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TracesSearchRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.expedia.open.tracing.api.TracesSearchRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TracesSearchRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.expedia.open.tracing.api.TracesSearchRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.expedia.open.tracing.api.TracesSearchRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * criteria for searching traces
   * </pre>
   *
   * Protobuf type {@code TracesSearchRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TracesSearchRequest)
      com.expedia.open.tracing.api.TracesSearchRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TracesSearchRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TracesSearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.expedia.open.tracing.api.TracesSearchRequest.class, com.expedia.open.tracing.api.TracesSearchRequest.Builder.class);
    }

    // Construct using com.expedia.open.tracing.api.TracesSearchRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFieldsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (fieldsBuilder_ == null) {
        fields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        fieldsBuilder_.clear();
      }
      startTime_ = 0L;

      endTime_ = 0L;

      limit_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TracesSearchRequest_descriptor;
    }

    public com.expedia.open.tracing.api.TracesSearchRequest getDefaultInstanceForType() {
      return com.expedia.open.tracing.api.TracesSearchRequest.getDefaultInstance();
    }

    public com.expedia.open.tracing.api.TracesSearchRequest build() {
      com.expedia.open.tracing.api.TracesSearchRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.expedia.open.tracing.api.TracesSearchRequest buildPartial() {
      com.expedia.open.tracing.api.TracesSearchRequest result = new com.expedia.open.tracing.api.TracesSearchRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (fieldsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          fields_ = java.util.Collections.unmodifiableList(fields_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fields_ = fields_;
      } else {
        result.fields_ = fieldsBuilder_.build();
      }
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.limit_ = limit_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.expedia.open.tracing.api.TracesSearchRequest) {
        return mergeFrom((com.expedia.open.tracing.api.TracesSearchRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.expedia.open.tracing.api.TracesSearchRequest other) {
      if (other == com.expedia.open.tracing.api.TracesSearchRequest.getDefaultInstance()) return this;
      if (fieldsBuilder_ == null) {
        if (!other.fields_.isEmpty()) {
          if (fields_.isEmpty()) {
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFieldsIsMutable();
            fields_.addAll(other.fields_);
          }
          onChanged();
        }
      } else {
        if (!other.fields_.isEmpty()) {
          if (fieldsBuilder_.isEmpty()) {
            fieldsBuilder_.dispose();
            fieldsBuilder_ = null;
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000001);
            fieldsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFieldsFieldBuilder() : null;
          } else {
            fieldsBuilder_.addAllMessages(other.fields_);
          }
        }
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.getLimit() != 0) {
        setLimit(other.getLimit());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.expedia.open.tracing.api.TracesSearchRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.expedia.open.tracing.api.TracesSearchRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.expedia.open.tracing.api.Field> fields_ =
      java.util.Collections.emptyList();
    private void ensureFieldsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        fields_ = new java.util.ArrayList<com.expedia.open.tracing.api.Field>(fields_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.expedia.open.tracing.api.Field, com.expedia.open.tracing.api.Field.Builder, com.expedia.open.tracing.api.FieldOrBuilder> fieldsBuilder_;

    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public java.util.List<com.expedia.open.tracing.api.Field> getFieldsList() {
      if (fieldsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fields_);
      } else {
        return fieldsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public int getFieldsCount() {
      if (fieldsBuilder_ == null) {
        return fields_.size();
      } else {
        return fieldsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public com.expedia.open.tracing.api.Field getFields(int index) {
      if (fieldsBuilder_ == null) {
        return fields_.get(index);
      } else {
        return fieldsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public Builder setFields(
        int index, com.expedia.open.tracing.api.Field value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.set(index, value);
        onChanged();
      } else {
        fieldsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public Builder setFields(
        int index, com.expedia.open.tracing.api.Field.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.set(index, builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public Builder addFields(com.expedia.open.tracing.api.Field value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
      } else {
        fieldsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public Builder addFields(
        int index, com.expedia.open.tracing.api.Field value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.add(index, value);
        onChanged();
      } else {
        fieldsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public Builder addFields(
        com.expedia.open.tracing.api.Field.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.add(builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public Builder addFields(
        int index, com.expedia.open.tracing.api.Field.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.add(index, builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public Builder addAllFields(
        java.lang.Iterable<? extends com.expedia.open.tracing.api.Field> values) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fields_);
        onChanged();
      } else {
        fieldsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public Builder clearFields() {
      if (fieldsBuilder_ == null) {
        fields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        fieldsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public Builder removeFields(int index) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.remove(index);
        onChanged();
      } else {
        fieldsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public com.expedia.open.tracing.api.Field.Builder getFieldsBuilder(
        int index) {
      return getFieldsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public com.expedia.open.tracing.api.FieldOrBuilder getFieldsOrBuilder(
        int index) {
      if (fieldsBuilder_ == null) {
        return fields_.get(index);  } else {
        return fieldsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public java.util.List<? extends com.expedia.open.tracing.api.FieldOrBuilder> 
         getFieldsOrBuilderList() {
      if (fieldsBuilder_ != null) {
        return fieldsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fields_);
      }
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public com.expedia.open.tracing.api.Field.Builder addFieldsBuilder() {
      return getFieldsFieldBuilder().addBuilder(
          com.expedia.open.tracing.api.Field.getDefaultInstance());
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public com.expedia.open.tracing.api.Field.Builder addFieldsBuilder(
        int index) {
      return getFieldsFieldBuilder().addBuilder(
          index, com.expedia.open.tracing.api.Field.getDefaultInstance());
    }
    /**
     * <pre>
     * fields to filter traces
     * </pre>
     *
     * <code>repeated .Field fields = 1;</code>
     */
    public java.util.List<com.expedia.open.tracing.api.Field.Builder> 
         getFieldsBuilderList() {
      return getFieldsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.expedia.open.tracing.api.Field, com.expedia.open.tracing.api.Field.Builder, com.expedia.open.tracing.api.FieldOrBuilder> 
        getFieldsFieldBuilder() {
      if (fieldsBuilder_ == null) {
        fieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.expedia.open.tracing.api.Field, com.expedia.open.tracing.api.Field.Builder, com.expedia.open.tracing.api.FieldOrBuilder>(
                fields_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        fields_ = null;
      }
      return fieldsBuilder_;
    }

    private long startTime_ ;
    /**
     * <pre>
     * search window start time in microseconds time from epoch
     * </pre>
     *
     * <code>optional int64 startTime = 2;</code>
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <pre>
     * search window start time in microseconds time from epoch
     * </pre>
     *
     * <code>optional int64 startTime = 2;</code>
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * search window start time in microseconds time from epoch
     * </pre>
     *
     * <code>optional int64 startTime = 2;</code>
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <pre>
     * search window end time in microseconds time from epoch
     * </pre>
     *
     * <code>optional int64 endTime = 3;</code>
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <pre>
     * search window end time in microseconds time from epoch
     * </pre>
     *
     * <code>optional int64 endTime = 3;</code>
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * search window end time in microseconds time from epoch
     * </pre>
     *
     * <code>optional int64 endTime = 3;</code>
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private int limit_ ;
    /**
     * <pre>
     * limit on number of results to return
     * </pre>
     *
     * <code>optional int32 limit = 4;</code>
     */
    public int getLimit() {
      return limit_;
    }
    /**
     * <pre>
     * limit on number of results to return
     * </pre>
     *
     * <code>optional int32 limit = 4;</code>
     */
    public Builder setLimit(int value) {
      
      limit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * limit on number of results to return
     * </pre>
     *
     * <code>optional int32 limit = 4;</code>
     */
    public Builder clearLimit() {
      
      limit_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:TracesSearchRequest)
  }

  // @@protoc_insertion_point(class_scope:TracesSearchRequest)
  private static final com.expedia.open.tracing.api.TracesSearchRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.expedia.open.tracing.api.TracesSearchRequest();
  }

  public static com.expedia.open.tracing.api.TracesSearchRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TracesSearchRequest>
      PARSER = new com.google.protobuf.AbstractParser<TracesSearchRequest>() {
    public TracesSearchRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TracesSearchRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TracesSearchRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TracesSearchRequest> getParserForType() {
    return PARSER;
  }

  public com.expedia.open.tracing.api.TracesSearchRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

