// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

public interface TraceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Trace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string traceId = 1;</code>
   */
  java.lang.String getTraceId();
  /**
   * <code>optional string traceId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>repeated .Span childSpans = 2;</code>
   */
  java.util.List<com.expedia.open.tracing.Span> 
      getChildSpansList();
  /**
   * <code>repeated .Span childSpans = 2;</code>
   */
  com.expedia.open.tracing.Span getChildSpans(int index);
  /**
   * <code>repeated .Span childSpans = 2;</code>
   */
  int getChildSpansCount();
  /**
   * <code>repeated .Span childSpans = 2;</code>
   */
  java.util.List<? extends com.expedia.open.tracing.SpanOrBuilder> 
      getChildSpansOrBuilderList();
  /**
   * <code>repeated .Span childSpans = 2;</code>
   */
  com.expedia.open.tracing.SpanOrBuilder getChildSpansOrBuilder(
      int index);
}
