// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

/**
 * <pre>
 * list of filtered traces
 * </pre>
 *
 * Protobuf type {@code TracesSearchResult}
 */
public  final class TracesSearchResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TracesSearchResult)
    TracesSearchResultOrBuilder {
  // Use TracesSearchResult.newBuilder() to construct.
  private TracesSearchResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TracesSearchResult() {
    traces_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TracesSearchResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              traces_ = new java.util.ArrayList<com.expedia.open.tracing.api.Trace>();
              mutable_bitField0_ |= 0x00000001;
            }
            traces_.add(
                input.readMessage(com.expedia.open.tracing.api.Trace.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        traces_ = java.util.Collections.unmodifiableList(traces_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TracesSearchResult_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TracesSearchResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.expedia.open.tracing.api.TracesSearchResult.class, com.expedia.open.tracing.api.TracesSearchResult.Builder.class);
  }

  public static final int TRACES_FIELD_NUMBER = 1;
  private java.util.List<com.expedia.open.tracing.api.Trace> traces_;
  /**
   * <code>repeated .Trace traces = 1;</code>
   */
  public java.util.List<com.expedia.open.tracing.api.Trace> getTracesList() {
    return traces_;
  }
  /**
   * <code>repeated .Trace traces = 1;</code>
   */
  public java.util.List<? extends com.expedia.open.tracing.api.TraceOrBuilder> 
      getTracesOrBuilderList() {
    return traces_;
  }
  /**
   * <code>repeated .Trace traces = 1;</code>
   */
  public int getTracesCount() {
    return traces_.size();
  }
  /**
   * <code>repeated .Trace traces = 1;</code>
   */
  public com.expedia.open.tracing.api.Trace getTraces(int index) {
    return traces_.get(index);
  }
  /**
   * <code>repeated .Trace traces = 1;</code>
   */
  public com.expedia.open.tracing.api.TraceOrBuilder getTracesOrBuilder(
      int index) {
    return traces_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < traces_.size(); i++) {
      output.writeMessage(1, traces_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < traces_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, traces_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.expedia.open.tracing.api.TracesSearchResult)) {
      return super.equals(obj);
    }
    com.expedia.open.tracing.api.TracesSearchResult other = (com.expedia.open.tracing.api.TracesSearchResult) obj;

    boolean result = true;
    result = result && getTracesList()
        .equals(other.getTracesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getTracesCount() > 0) {
      hash = (37 * hash) + TRACES_FIELD_NUMBER;
      hash = (53 * hash) + getTracesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.expedia.open.tracing.api.TracesSearchResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.expedia.open.tracing.api.TracesSearchResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TracesSearchResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.expedia.open.tracing.api.TracesSearchResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TracesSearchResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.expedia.open.tracing.api.TracesSearchResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TracesSearchResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.expedia.open.tracing.api.TracesSearchResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.expedia.open.tracing.api.TracesSearchResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.expedia.open.tracing.api.TracesSearchResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.expedia.open.tracing.api.TracesSearchResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * list of filtered traces
   * </pre>
   *
   * Protobuf type {@code TracesSearchResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TracesSearchResult)
      com.expedia.open.tracing.api.TracesSearchResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TracesSearchResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TracesSearchResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.expedia.open.tracing.api.TracesSearchResult.class, com.expedia.open.tracing.api.TracesSearchResult.Builder.class);
    }

    // Construct using com.expedia.open.tracing.api.TracesSearchResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTracesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (tracesBuilder_ == null) {
        traces_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        tracesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.expedia.open.tracing.api.TraceReaderOuterClass.internal_static_TracesSearchResult_descriptor;
    }

    public com.expedia.open.tracing.api.TracesSearchResult getDefaultInstanceForType() {
      return com.expedia.open.tracing.api.TracesSearchResult.getDefaultInstance();
    }

    public com.expedia.open.tracing.api.TracesSearchResult build() {
      com.expedia.open.tracing.api.TracesSearchResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.expedia.open.tracing.api.TracesSearchResult buildPartial() {
      com.expedia.open.tracing.api.TracesSearchResult result = new com.expedia.open.tracing.api.TracesSearchResult(this);
      int from_bitField0_ = bitField0_;
      if (tracesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          traces_ = java.util.Collections.unmodifiableList(traces_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.traces_ = traces_;
      } else {
        result.traces_ = tracesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.expedia.open.tracing.api.TracesSearchResult) {
        return mergeFrom((com.expedia.open.tracing.api.TracesSearchResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.expedia.open.tracing.api.TracesSearchResult other) {
      if (other == com.expedia.open.tracing.api.TracesSearchResult.getDefaultInstance()) return this;
      if (tracesBuilder_ == null) {
        if (!other.traces_.isEmpty()) {
          if (traces_.isEmpty()) {
            traces_ = other.traces_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTracesIsMutable();
            traces_.addAll(other.traces_);
          }
          onChanged();
        }
      } else {
        if (!other.traces_.isEmpty()) {
          if (tracesBuilder_.isEmpty()) {
            tracesBuilder_.dispose();
            tracesBuilder_ = null;
            traces_ = other.traces_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tracesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTracesFieldBuilder() : null;
          } else {
            tracesBuilder_.addAllMessages(other.traces_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.expedia.open.tracing.api.TracesSearchResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.expedia.open.tracing.api.TracesSearchResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.expedia.open.tracing.api.Trace> traces_ =
      java.util.Collections.emptyList();
    private void ensureTracesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        traces_ = new java.util.ArrayList<com.expedia.open.tracing.api.Trace>(traces_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.expedia.open.tracing.api.Trace, com.expedia.open.tracing.api.Trace.Builder, com.expedia.open.tracing.api.TraceOrBuilder> tracesBuilder_;

    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public java.util.List<com.expedia.open.tracing.api.Trace> getTracesList() {
      if (tracesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(traces_);
      } else {
        return tracesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public int getTracesCount() {
      if (tracesBuilder_ == null) {
        return traces_.size();
      } else {
        return tracesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public com.expedia.open.tracing.api.Trace getTraces(int index) {
      if (tracesBuilder_ == null) {
        return traces_.get(index);
      } else {
        return tracesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public Builder setTraces(
        int index, com.expedia.open.tracing.api.Trace value) {
      if (tracesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTracesIsMutable();
        traces_.set(index, value);
        onChanged();
      } else {
        tracesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public Builder setTraces(
        int index, com.expedia.open.tracing.api.Trace.Builder builderForValue) {
      if (tracesBuilder_ == null) {
        ensureTracesIsMutable();
        traces_.set(index, builderForValue.build());
        onChanged();
      } else {
        tracesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public Builder addTraces(com.expedia.open.tracing.api.Trace value) {
      if (tracesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTracesIsMutable();
        traces_.add(value);
        onChanged();
      } else {
        tracesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public Builder addTraces(
        int index, com.expedia.open.tracing.api.Trace value) {
      if (tracesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTracesIsMutable();
        traces_.add(index, value);
        onChanged();
      } else {
        tracesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public Builder addTraces(
        com.expedia.open.tracing.api.Trace.Builder builderForValue) {
      if (tracesBuilder_ == null) {
        ensureTracesIsMutable();
        traces_.add(builderForValue.build());
        onChanged();
      } else {
        tracesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public Builder addTraces(
        int index, com.expedia.open.tracing.api.Trace.Builder builderForValue) {
      if (tracesBuilder_ == null) {
        ensureTracesIsMutable();
        traces_.add(index, builderForValue.build());
        onChanged();
      } else {
        tracesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public Builder addAllTraces(
        java.lang.Iterable<? extends com.expedia.open.tracing.api.Trace> values) {
      if (tracesBuilder_ == null) {
        ensureTracesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, traces_);
        onChanged();
      } else {
        tracesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public Builder clearTraces() {
      if (tracesBuilder_ == null) {
        traces_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tracesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public Builder removeTraces(int index) {
      if (tracesBuilder_ == null) {
        ensureTracesIsMutable();
        traces_.remove(index);
        onChanged();
      } else {
        tracesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public com.expedia.open.tracing.api.Trace.Builder getTracesBuilder(
        int index) {
      return getTracesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public com.expedia.open.tracing.api.TraceOrBuilder getTracesOrBuilder(
        int index) {
      if (tracesBuilder_ == null) {
        return traces_.get(index);  } else {
        return tracesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public java.util.List<? extends com.expedia.open.tracing.api.TraceOrBuilder> 
         getTracesOrBuilderList() {
      if (tracesBuilder_ != null) {
        return tracesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(traces_);
      }
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public com.expedia.open.tracing.api.Trace.Builder addTracesBuilder() {
      return getTracesFieldBuilder().addBuilder(
          com.expedia.open.tracing.api.Trace.getDefaultInstance());
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public com.expedia.open.tracing.api.Trace.Builder addTracesBuilder(
        int index) {
      return getTracesFieldBuilder().addBuilder(
          index, com.expedia.open.tracing.api.Trace.getDefaultInstance());
    }
    /**
     * <code>repeated .Trace traces = 1;</code>
     */
    public java.util.List<com.expedia.open.tracing.api.Trace.Builder> 
         getTracesBuilderList() {
      return getTracesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.expedia.open.tracing.api.Trace, com.expedia.open.tracing.api.Trace.Builder, com.expedia.open.tracing.api.TraceOrBuilder> 
        getTracesFieldBuilder() {
      if (tracesBuilder_ == null) {
        tracesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.expedia.open.tracing.api.Trace, com.expedia.open.tracing.api.Trace.Builder, com.expedia.open.tracing.api.TraceOrBuilder>(
                traces_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        traces_ = null;
      }
      return tracesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:TracesSearchResult)
  }

  // @@protoc_insertion_point(class_scope:TracesSearchResult)
  private static final com.expedia.open.tracing.api.TracesSearchResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.expedia.open.tracing.api.TracesSearchResult();
  }

  public static com.expedia.open.tracing.api.TracesSearchResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TracesSearchResult>
      PARSER = new com.google.protobuf.AbstractParser<TracesSearchResult>() {
    public TracesSearchResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TracesSearchResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TracesSearchResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TracesSearchResult> getParserForType() {
    return PARSER;
  }

  public com.expedia.open.tracing.api.TracesSearchResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

