// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: span.proto

package com.expedia.open.tracing;

public interface SpanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Span)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unique trace id
   * </pre>
   *
   * <code>optional string traceId = 1;</code>
   */
  java.lang.String getTraceId();
  /**
   * <pre>
   * unique trace id
   * </pre>
   *
   * <code>optional string traceId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <pre>
   * unique span id
   * </pre>
   *
   * <code>optional string spanId = 2;</code>
   */
  java.lang.String getSpanId();
  /**
   * <pre>
   * unique span id
   * </pre>
   *
   * <code>optional string spanId = 2;</code>
   */
  com.google.protobuf.ByteString
      getSpanIdBytes();

  /**
   * <pre>
   * optional, a span can have its parent spanId
   * </pre>
   *
   * <code>optional string parentSpanId = 3;</code>
   */
  java.lang.String getParentSpanId();
  /**
   * <pre>
   * optional, a span can have its parent spanId
   * </pre>
   *
   * <code>optional string parentSpanId = 3;</code>
   */
  com.google.protobuf.ByteString
      getParentSpanIdBytes();

  /**
   * <pre>
   * name of service
   * </pre>
   *
   * <code>optional string serviceName = 4;</code>
   */
  java.lang.String getServiceName();
  /**
   * <pre>
   * name of service
   * </pre>
   *
   * <code>optional string serviceName = 4;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <pre>
   * name of operation
   * </pre>
   *
   * <code>optional string operationName = 5;</code>
   */
  java.lang.String getOperationName();
  /**
   * <pre>
   * name of operation
   * </pre>
   *
   * <code>optional string operationName = 5;</code>
   */
  com.google.protobuf.ByteString
      getOperationNameBytes();

  /**
   * <pre>
   * creation time of this span in microseconds since epoch
   * </pre>
   *
   * <code>optional int64 startTime = 6;</code>
   */
  long getStartTime();

  /**
   * <pre>
   * span duration in microseconds
   * </pre>
   *
   * <code>optional int64 duration = 7;</code>
   */
  long getDuration();

  /**
   * <pre>
   * arbitrary set of timestamp-aware key-value pairs
   * </pre>
   *
   * <code>repeated .Log logs = 8;</code>
   */
  java.util.List<com.expedia.open.tracing.Log> 
      getLogsList();
  /**
   * <pre>
   * arbitrary set of timestamp-aware key-value pairs
   * </pre>
   *
   * <code>repeated .Log logs = 8;</code>
   */
  com.expedia.open.tracing.Log getLogs(int index);
  /**
   * <pre>
   * arbitrary set of timestamp-aware key-value pairs
   * </pre>
   *
   * <code>repeated .Log logs = 8;</code>
   */
  int getLogsCount();
  /**
   * <pre>
   * arbitrary set of timestamp-aware key-value pairs
   * </pre>
   *
   * <code>repeated .Log logs = 8;</code>
   */
  java.util.List<? extends com.expedia.open.tracing.LogOrBuilder> 
      getLogsOrBuilderList();
  /**
   * <pre>
   * arbitrary set of timestamp-aware key-value pairs
   * </pre>
   *
   * <code>repeated .Log logs = 8;</code>
   */
  com.expedia.open.tracing.LogOrBuilder getLogsOrBuilder(
      int index);

  /**
   * <pre>
   * arbitrary set of key-value pairs
   * </pre>
   *
   * <code>repeated .Tag tags = 9;</code>
   */
  java.util.List<com.expedia.open.tracing.Tag> 
      getTagsList();
  /**
   * <pre>
   * arbitrary set of key-value pairs
   * </pre>
   *
   * <code>repeated .Tag tags = 9;</code>
   */
  com.expedia.open.tracing.Tag getTags(int index);
  /**
   * <pre>
   * arbitrary set of key-value pairs
   * </pre>
   *
   * <code>repeated .Tag tags = 9;</code>
   */
  int getTagsCount();
  /**
   * <pre>
   * arbitrary set of key-value pairs
   * </pre>
   *
   * <code>repeated .Tag tags = 9;</code>
   */
  java.util.List<? extends com.expedia.open.tracing.TagOrBuilder> 
      getTagsOrBuilderList();
  /**
   * <pre>
   * arbitrary set of key-value pairs
   * </pre>
   *
   * <code>repeated .Tag tags = 9;</code>
   */
  com.expedia.open.tracing.TagOrBuilder getTagsOrBuilder(
      int index);
}
