// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: span.proto

package com.expedia.open.tracing;

public final class SpanOuterClass {
  private SpanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Span_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Span_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Log_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Log_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tag_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tag_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Batch_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Batch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nspan.proto\"\266\001\n\004Span\022\017\n\007traceId\030\001 \001(\t\022\016" +
      "\n\006spanId\030\002 \001(\t\022\024\n\014parentSpanId\030\003 \001(\t\022\023\n\013" +
      "serviceName\030\004 \001(\t\022\025\n\roperationName\030\005 \001(\t" +
      "\022\021\n\tstartTime\030\006 \001(\003\022\020\n\010duration\030\007 \001(\003\022\022\n" +
      "\004logs\030\010 \003(\0132\004.Log\022\022\n\004tags\030\t \003(\0132\004.Tag\".\n" +
      "\003Log\022\021\n\ttimestamp\030\001 \001(\003\022\024\n\006fields\030\002 \003(\0132" +
      "\004.Tag\"\323\001\n\003Tag\022\013\n\003key\030\001 \001(\t\022\032\n\004type\030\002 \001(\016" +
      "2\014.Tag.TagType\022\016\n\004vStr\030\003 \001(\tH\000\022\017\n\005vLong\030" +
      "\004 \001(\003H\000\022\021\n\007vDouble\030\005 \001(\001H\000\022\017\n\005vBool\030\006 \001(" +
      "\010H\000\022\020\n\006vBytes\030\007 \001(\014H\000\"A\n\007TagType\022\n\n\006STRI",
      "NG\020\000\022\n\n\006DOUBLE\020\001\022\010\n\004BOOL\020\002\022\010\n\004LONG\020\003\022\n\n\006" +
      "BINARY\020\004B\t\n\007myvalue\"\035\n\005Batch\022\024\n\005spans\030\001 " +
      "\003(\0132\005.SpanB\034\n\030com.expedia.open.tracingP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Span_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Span_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Span_descriptor,
        new java.lang.String[] { "TraceId", "SpanId", "ParentSpanId", "ServiceName", "OperationName", "StartTime", "Duration", "Logs", "Tags", });
    internal_static_Log_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Log_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Log_descriptor,
        new java.lang.String[] { "Timestamp", "Fields", });
    internal_static_Tag_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Tag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tag_descriptor,
        new java.lang.String[] { "Key", "Type", "VStr", "VLong", "VDouble", "VBool", "VBytes", "Myvalue", });
    internal_static_Batch_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Batch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Batch_descriptor,
        new java.lang.String[] { "Spans", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
