# Permalinks
permalink:           pretty

# Jekyll 3
gems: [jekyll-paginate]
paginate_path: "page:num"

# Setup
title:               Maracas
tagline:             'The API-client co-evolution project'
description:         'Maracas is a source code and bytecode analysis framework --written in Rascal-- that is designed to support the co-evolution of Java APIs and client code.'
url:                 https://github.com/crossminer/maracas
baseurl:             '/maracas'
paginate:            5

# About/contact
author:
  name:              lmove

# Custom vars
version:             0.0.1
